config/routes.rb
Wd::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "log_in", sign_out: "log_out"}


  resources :people do
    get "revisions", :on => :member
  end
  resources :person_uploads
  resources :person_veil_passes, :only => [:create, :destroy, :update,]
  resources :campaigns

  resource :search, :only => :show
  resource :portal, :only => :show

  root :to => "portals#show"
end

app/models/person.rb
class Person < ActiveRecord::Base
  include PgSearch

  belongs_to :campaign, :inverse_of => :people, :touch => true
  has_one :dm, :through => :campaign
  has_many :uploads,
    :class_name => "PersonUpload",
    :dependent => :destroy,
    :inverse_of => :person
  has_many :veil_passes,
    :class_name => "PersonVeilPass",
    :dependent => :destroy,
    :inverse_of => :person do
    def users_ids
      all.map(&:user_id)
    end
  end

  pg_search_scope :full_search, {
    :against => {:name => "A", :public_description => "B",},
    :using => {
      :tsearch => {:prefix => true,},
    },
  }

  validates :name, :presence => true, :uniqueness => {:scope => :campaign_id}
  validates :campaign, :presence => true

  accepts_nested_attributes_for :uploads,
    :allow_destroy => true,
    :reject_if => proc {|attr| attr["id"].blank? && attr["upload"].blank? && attr["upload_cache"].blank?}
  accepts_nested_attributes_for :veil_passes,
    :allow_destroy => true,
    :reject_if => proc {|attr| attr["id"].blank? && (attr["person_id"].blank? || attr["user_id"].blank?)}

  attr_accessible :name,
                  :description,
                  :private,
                  :uploads_attributes,
                  :veil_passes_attributes

  has_paper_trail :on => [:update,], :ignore => [:private,]

  before_save :update_public_description


  def self.recently_updated(num=5)
    order("people.created_at DESC").limit(num)
  end


  def visible_uploads
    uploads.with_permissions_to(:read).order("person_uploads.created_at")
  end


  private

  def update_public_description
    if description_changed?
      self.public_description = description_with_dm_and_vp_removed
    end
  end

  def description_with_dm_and_vp_removed
    public_xslt =<<EOF
<?xml version='1.0' encoding='utf-8' ?>
<xsl:stylesheet version='1.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform'>

  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match='//*[@class="dm"]' />
  <xsl:template match='//*[@class="vp"]' />
</xsl:stylesheet>
EOF
    renderer = WdMarkdown.new(with_toc_data: true)
    markdown = Redcarpet::Markdown.new(renderer, tables: true, fenced_code_blocks: true)
    safe = markdown.render(ERB::Util.h(description))

    xslt = Nokogiri::XSLT(public_xslt)
    doc = Nokogiri::XML("<div>" + safe + "</div>")
    transformed = xslt.transform(doc)
    transformed.to_html.html_safe
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :edit, :new, :update, :changes]
  before_filter :require_current_campaign, :except => [:edit, :show, :update,]
  filter_resource_access :additional_member => {:changes => :update}


  def revisions
    @rev_left = params[:rev_left].to_i - 1
    @rev_right = params[:rev_right].to_i - 1
    @ver_left = @person.versions[@rev_left]
    @ver_right = @person.versions[@rev_right]
    @person_left = @ver_left ? @ver_left.reify : @person
    @person_right = @ver_right ? @ver_right.reify : @person
  end

  def create
    if @person.save
      flash[:notice] = "Person created successfully"
      redirect_to @person
    else
      render :action => "new"
    end
  end

  def destroy
    if @person.destroy
      flash[:notice] = "Person destroyed successfully"
    else
      flash[:error] = "Error deleting person"
    end
    redirect_to people_path
  end

  def index
    @people = current_campaign.people.with_permissions_to(:read)
  end

  def update
    if @person.update_attributes(params[:person])
      flash[:notice] = "Person updated successfully"
      redirect_to @person
    else
      render :action => "edit"
    end
  end


  protected

  def load_person
    if ["edit", "show", "update",].include?(params[:action])
      @person = Person.find(params[:id])
      self.current_campaign = @person.campaign
    else
      @person = current_campaign.people.find(params[:id])
    end
  end

  def new_person_from_params
    @person = current_campaign.people.build(params[:person])
  end

end

app/helpers/people_helper.rb
module PeopleHelper

  def class_for_upload(upload)
    if upload.visible_with_vp
      "vp"
    elsif upload.private
      "dm"
    else
      ""
    end
  end
end

app/views/people/_changes.html.haml
.changes

  .left
    %h2
      %span Rev #{@rev_left+1} (#{date_left})
    .contents
      %ol
        = list_of(output_left) do |line|
          = line

  .right
    %h2
      %span Rev #{@rev_right+1} (#{date_right})
    .contents
      %ol
        = list_of(output_right) do |line|
          = line

  .clear

app/views/people/_form.html.haml
= form_for(@person) do |f|
  .field
    = f.label("name")
    = f.text_field("name")
    = f.error_message_on("name")
  .field
    = f.label("description")
    = f.text_area("description")
    = f.error_message_on("description")
  .field
    = f.check_box("private")
    = f.label("private", nil, class: "inline")
    = f.error_message_on("private")
  %fieldset
    %legend Uploads
    .wrap
      = f.has_many_fields_for("uploads", @person.uploads) do |ff|
        = render("upload", ff: ff, upload: ff.object)


  %fieldset
    %legend Veil Passes
    .wrap
      %table{cellpadding: 0, cellspacing: 0}
        %thead
          %tr
            %th User
            %th Delete
        %tbody
          = f.has_many_fields_for("veil_passes", @person.veil_passes) do |ff|
            = render("/shared/veil_pass_form", ff: ff, veil_pass: ff.object)

  .actions
    .left
      = f.submit
      = cancel_button(@person)
    .right
      = delete_button(@person) unless @person.new_record?

app/views/people/_upload.html.haml
.field
  - if ff.object.persisted?
    = ff.label("_destroy", image_tag(upload.thumb.display_url, size: "110x110"))
    = File.basename(upload.url)
  - else
    = ff.hidden_field("upload_cache")
    = ff.label("upload", image_tag(upload.thumb.display_url, size: "110x110"))
    = ff.label("upload", "Upload an image or other file")
    %br
    = ff.file_field("upload")
    = ff.error_message_on("upload")
  %br
  = ff.label("caption")
  = ff.text_field("caption")
  = ff.error_message_on("caption")
  %br
  = ff.check_box("private")
  = ff.label("private", nil, class: "inline")
  = ff.error_message_on("private")
  %br
  = ff.check_box("visible_with_vp")
  = ff.label("visible_with_vp", "Visible with Veil Pass", class: "inline")
  = ff.error_message_on("visible_with_vp")
  - if ff.object.persisted?
    %br
    = ff.check_box("_destroy")
    = ff.label("_destroy", "Delete", class: "inline")
    = ff.error_message_on("_destroy")

app/views/people/_veil_pass.html.haml
%tr
  %td
    = ff.hidden_field("person_id")
    = ff.collection_select("user_id", User.order("users.name").all - [current_user], :id, :name, veil_pass.errors.present? ? {:include_blank => true} : {:prompt => true})
    = ff.error_message_on("user_id")
  %td.center
    = ff.check_box("includes_uploads")
    = ff.error_message_on("includes_uploads")
  %td.center
    - if veil_pass.persisted?
      = ff.check_box("_destroy")
      = ff.error_message_on("_destroy")

app/views/people/edit.html.haml
- title("Edit Person")

%ul.breadcrumbs
  %li= link_to(current_campaign.name, current_campaign)
  %li= link_to("People", people_path)
  %li= link_to(@person.name, @person)
  %li Edit Person

%h1 Edit Person

= render("form")

app/views/people/index.html.haml
- title("People")

%ul.breadcrumbs
  %li= link_to(current_campaign.name, current_campaign)
  %li People

%h1 People

%table
  %thead
    %tr
      %th.num
      %th Name

  %tbody
    - @people.order("people.name").each_with_index do |person, idx|
      %tr{:class => cycle("odd", "even")}
        %td.num
          = succeed(".") do
            = 1 + idx
        %td
          = link_to(person.name, person)
          = private_icon(person)

.actions
  .left
    = new_button(new_person_path)

app/views/people/new.html.haml
- title("New Person")

%h1 New Person

= form_for(@person) do |f|
  = render("form", f: f)
  = f.submit

app/views/people/revisions.html.haml
- title("Revisions")

%h1
  Revisions for #{@person.name}

%ul.breadcrumbs
  %li= link_to(current_campaign.name, current_campaign)
  %li= link_to("People", people_path)
  %li= link_to(@person.name, @person)
  %li Revisions

= show_changes(@person_left.description, @person_left.updated_at,
               @person_right.description, @person_right.updated_at)

%h3 Key
.changes
  .key
    .change Line changed
    %ins.insert Line inserted
    %del.delete Line deleted
  .clear

%h2 Select Revisions
= revisions_form_for(@person) do |f|
  = f.revision_picker(:left, :selected => @rev_left+1)
  and
  = f.revision_picker(:right, :selected => @rev_right+1)
  = f.submit("View Changes")
  = link_to("Back", @person)

app/views/people/show.html.haml
- title("Person: #{@person.name}")

- html = toc(@person.description)
- if html.present?
  .toc
    %h3 Table of Contents
    = html

%ul.breadcrumbs
  %li= link_to(current_campaign.name, current_campaign)
  %li= link_to("People", people_path)
  %li= @person.name

%h1{style: "clear: left"}
  = append_private_icon(@person, highlight(@person.name, params[:q]))

= description(@person.description)

= render("/shared/veil_passes", subject: @person)

- if permitted_to?(:edit, @person)
  .actions
    .left
      = edit_button(@person)
  .clear

%p
  Last updated #{@person.updated_at.to_s(:long)}
  - if permitted_to?(:edit, @person)
    %br
    Revised #{pluralize(@person.versions.count, "time")}.
    - if @person.versions.count > 0
      = link_to("View revisions", revisions_person_path(@person))

- if visible_due_to_veil_pass?(@person)
  %p.veil_pass_description
    This page is private. You are able to view this page because
    #{current_campaign.dm_name} has issued you a Veil Pass.  This pass allows
    you to view information that is otherwise considered private.  <em>Be
    careful how you share this information with other players</em>.

= content_for(:sidebar) do
  - if @person.visible_uploads.present?
    - @person.visible_uploads.each do |upload|
      .upload{class: class_for_upload(upload)}
        = link_to(upload.url, class: "overlay_container") do
          = image_tag(upload.sidebar.display_url, :size => "230x230")
          = private_upload_icon(upload)
        .caption
          = link_to(upload.caption, upload.url)
  - if is_dm?
    %ul
      %li= link_to("Show DM view", "", id: "show_dm_view")
      %li= link_to("Show VP view", "", id: "show_vp_view")
      %li= link_to("Show Public view", "", id: "show_public_view")

= content_for(:head) do
  :javascript
    $(function () {
      function show_dm_view() {
        $(".dm").show();
        $(".vp").show();
      }

      function show_vp_view() {
        $(".dm").hide();
        $(".vp").show();
      }

      function show_public_view() {
        $(".dm").hide();
        $(".vp").hide();
      }

      $("#show_dm_view").click(function () {show_dm_view(); return false;});
      $("#show_vp_view").click(function () {show_vp_view(); return false;});
      $("#show_public_view").click(function () {show_public_view(); return false;});
    })