config/routes.rb
Wd::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "log_in", sign_out: "log_out"}


  resources :people do
    get "revisions", :on => :member
  end
  resources :person_uploads
  resources :person_veil_passes, :only => [:create, :destroy, :update,]
  resources :campaigns

  resource :search, :only => :show
  resource :portal, :only => :show

  root :to => "portals#show"
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  include PgSearch

  belongs_to :dm,
    :class_name => "User",
    :foreign_key => "dm_id",
    :inverse_of => :campaigns
  has_many :people, :inverse_of => :campaign, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => {:scope => :dm_id}
  validates :dm, :presence => true

  delegate :name, :to => :dm, :prefix => true

  attr_accessible :name, :description, :private


  def self.recently_updated(num=5)
    order("updated_at DESC").limit(num)
  end

  def organizations
    # placeholder
    Campaign.scoped
  end

  def places
    # placeholder
    Campaign.scoped
  end

  def things
    # placeholder
    Campaign.scoped
  end

  def visible_people
    people.with_permissions_to(:read)
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :edit, :new, :update,]
  filter_resource_access


  def create
    if @campaign.save
      flash["notice"] = "Campaign created successfully"
      redirect_to @campaign
    else
      render :action => "new"
    end
  end

  def destroy
    if @campaign.destroy
      flash[:notice] = "Campaign deleted successfully"
    else
      flash[:error] = "Error deleting campaign"
    end
    redirect_to campaigns_path
  end

  def index
    @campaigns = Campaign.with_permissions_to(:read)
  end

  def show
    @recent_people = @campaign.people
      .with_permissions_to(:read)
      .recently_updated
  end

  def update
    if @campaign.update_attributes(params[:campaign])
      flash["notice"] = "Campaign updated successfully"
      redirect_to @campaign
    else
      render :action => "edit"
    end
  end


  protected

  def load_campaign
    if "show" == params[:action]
      @campaign = Campaign.find(params[:id])
    else
      @campaign = current_user.campaigns.find(params[:id])
    end
  end

  def new_campaign_from_params
    @campaign = current_user.campaigns.build(params[:campaign])
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def campaign_description(desc)
    desc ||= "No description."
    text = markdown(linkify(desc))
  end

end

app/views/campaigns/_form.html.haml
= form_for(@campaign) do |f|
  .field
    = f.label("name")
    = f.text_field("name")
    = f.error_message_on("name")
  .field
    = f.label("description")
    = f.text_area("description")
    = f.error_message_on("description")
  .field
    = f.label("private", nil, class: "inline")
    = f.check_box("private")
    = f.error_message_on("private")
  .actions
    .left
      = f.submit
      = cancel_button(@campaign)
    .right
      = delete_button(@campaign) unless @campaign.new_record?

app/views/campaigns/edit.html.haml
- title("Edit Campaign")

%h1 Edit Campaign

= render("form")

app/views/campaigns/index.html.haml
%h1 Campaigns

%table
  %thead
    %tr
      %th Name
      %th DM

  %tbody
    - @campaigns.each do |campaign|
      %tr{:class => cycle("odd", "even")}
        %td
          = link_to(campaign.name, campaign)
          = private_icon(campaign)
        %td= campaign.dm_name

.actions
  .left
    = new_button(new_campaign_path)

app/views/campaigns/new.html.haml
- title("New Campaign")

%h1 New Campaign

= render("form")

app/views/campaigns/show.html.haml
- title("Campaign: #{@campaign.name}")

%h1= @campaign.name

= campaign_description(@campaign.description)

%ul.menu
  %li
    = link_to("People", people_path)

.actions
  .left
    = edit_button(@campaign)

= content_for(:head) do
  = auto_discovery_link_tag(:rss, :format => "rss")