config/routes.rb
Wd::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "log_in", sign_out: "log_out"}


  resources :people do
    get "revisions", :on => :member
  end
  resources :person_uploads
  resources :person_veil_passes, :only => [:create, :destroy, :update,]
  resources :campaigns

  resource :search, :only => :show
  resource :portal, :only => :show

  root :to => "portals#show"
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title<
      World Diary
      - if content_for?(:title)
        = precede(": ") do
          = yield(:title)
    = favicon_link_tag
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Forum"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = content_for(:head) if content_for?(:head)
  %body#top{class: page_class}
    #wrap
      = render_flash
      #header
        .left
          %ul.menu
            %li
              = link_to("Home", root_path)
            %li
              = link_to("Campaigns", campaigns_path)
            %li
              = form_tag(search_path, :method => :get) do
                = search_field_tag("q")
                = submit_tag("Search")
        .right
          %ul.session
            - if user_signed_in?
              %li
                = link_to(current_user.name, edit_user_registration_path)
              %li
                = link_to("Log out", destroy_user_session_path, :method => :delete)
            - else
              %li
                = link_to("Sign up", new_user_registration_path)
              %li
                = link_to("Log in", new_user_session_path)
        .clear
      #content
        .main
          = yield
        .sidebar
          = content_for(:sidebar) if content_for?(:sidebar)
      #footer
        Copyright 2011 Eric Wollesen.  All rights reserved.